1                   cgitb               multicall           sspi
__future__          charset_normalizer  multidict           sspicon
__main__            chunk               multiprocessing     stackviewer
_abc                cmath               nest_asyncio        stat
_aix_support        cmd                 netbios             statistics
_ast                code                netrc               statusbar
_asyncio            codecontext         nntplib             string
_bisect             codecs              nt                  stringprep
_blake2             codeop              ntpath              struct
_bootsubprocess     collections         ntsecuritycon       subprocess
_bz2                colorama            nturl2path          sunau
_cffi_backend       colorizer           numbers             symtable
_codecs             colorsys            odbc                sys
_codecs_cn          commctrl            opcode              sysconfig
_codecs_hk          commonmark          operator            tabnanny
_codecs_iso2022     compileall          optparse            tarfile
_codecs_jp          concurrent          os                  telnetlib
_codecs_kr          config              outwin              tempfile
_codecs_tw          config_key          p                   terminado
_collections        configdialog        packaging           test
_collections_abc    configparser        pandocfilters       textview
_compat_pickle      contextlib          parenmatch          textwrap
_compression        contextvars         parso               this
_contextvars        copy                pathbrowser         threading
_csv                copyreg             pathlib             time
_ctypes             crypt               pdb                 timeit
_ctypes_test        cryptography        percolator          timer
_datetime           csv                 perfmon             tinycss2
_decimal            ctypes              pickle              tkinter
_distutils_hack     curses              pickleshare         token
_elementtree        dataclasses         pickletools         tokenize
_functools          datetime            pip                 tomli
_hashlib            dateutil            pipes               tooltip
_heapq              dbi                 pkg_resources       tornado
_imp                dbm                 pkgutil             trace
_io                 dde                 platform            traceback
_json               debugger            plistlib            tracemalloc
_locale             debugger_r          pluggy              traitlets
_lsprof             debugobj            poplib              tree
_lzma               debugobj_r          posixpath           tty
_markupbase         decimal             pprint              turtle
_md5                defusedxml          priya               turtledemo
_msi                delegator           profile             types
_multibytecodec     difflib             prometheus_client   typing
_multiprocessing    dis                 prompt_toolkit      tzdata
_opcode             distutils           pstats              undo
_operator           django              psutil              unicodedata
_osx_support        doctest             pty                 unittest
_overlapped         dynoption           pure_eval           urllib
_pickle             editor              pvectorc            urllib3
_py_abc             email               py                  util
_pydecimal          encodings           py_compile          uu
_pyio               ensurepip           pyclbr              uuid
_pyrsistent_version enum                pycparser           venv
_pytest             errno               pydoc               warnings
_queue              executing           pydoc_data          wave
_random             fastjsonschema      pyexpat             wcwidth
_sha1               faulthandler        pygame              weakref
_sha256             filecmp             pygments            webbrowser
_sha3               fileinput           pymysql             webencodings
_sha512             filelist            pyparse             websocket
_signal             fnmatch             pyparsing           win2kras
_sitebuiltins       format              pyrsistent          win32api
_socket             fractions           pyshell             win32clipboard
_sqlite3            ftplib              pytest              win32com
_sre                functools           pythoncom           win32con
_ssl                gc                  pytz                win32console
_stat               genericpath         pywin               win32cred
_statistics         getopt              pywin32_bootstrap   win32crypt
_string             getpass             pywin32_testutil    win32cryptcon
_strptime           gettext             pywintypes          win32event
_struct             glob                query               win32evtlog
_symtable           graphlib            queue               win32evtlogutil
_testbuffer         grep                quopri              win32file
_testcapi           gzip                ramesh              win32gui
_testconsole        hashlib             random              win32gui_struct
_testimportmultiple heapq               rasutil             win32help
_testinternalcapi   help                ravindraass         win32inet
_testmultiphase     help_about          re                  win32inetcon
_thread             history             redirector          win32job
_threading_local    hmac                regcheck            win32lz
_tkinter            html                regutil             win32net
_tracemalloc        http                replace             win32netcon
_uuid               httpie              reprlib             win32pdh
_warnings           hyperparser         requests            win32pdhquery
_weakref            idle                requests_toolbelt   win32pdhutil
_weakrefset         idle_test           rest_framework      win32pipe
_win32sysloader     idlelib             rest_framework_simplejwt win32print
_winapi             idna                rich                win32process
_winxptheme         imaplib             rlcompleter         win32profile
_xxsubinterpreters  imghdr              rpc                 win32ras
_zoneinfo           imp                 run                 win32rcparser
abc                 importlib           runpy               win32security
adodbapi            iniconfig           runscript           win32service
afxres              inspect             sched               win32serviceutil
aifc                io                  scrolledlist        win32timezone
antigravity         iomenu              search              win32trace
argparse            ipaddress           searchbase          win32traceutil
array               ipython_genutils    searchengine        win32transaction
asgiref             isapi               secrets             win32ts
assignment2(14-07-2022) itertools           select              win32ui
ast                 json                selectors           win32uiole
asynchat            json5               send2trash          win32verstamp
asyncio             jupyter             servicemanager      win32wnet
asyncore            jupyter_core        setuptools          window
atexit              jupyterlab_pygments shelve              winerror
atomicwrites        jwt                 shlex               winioctlcon
attr                keyword             shutil              winnt
attrs               lib2to3             sidebar             winperf
audioop             linecache           signal              winpty
autocomplete        locale              simplejwt           winreg
autocomplete_w      logging             site                winsound
autoexpand          lzma                six                 winxpgui
backcall            macosx              smtpd               winxptheme
base64              mailbox             smtplib             wsgiref
bdb                 mailcap             sndhdr              xdrlib
binascii            mainmenu            sniffio             xml
binhex              markupsafe          socket              xmlrpc
bisect              marshal             socketserver        xxsubtype
browser             math                socks               zipapp
builtins            matplotlib_inline   sockshandler        zipfile
bz2                 mimetypes           soupsieve           zipimport
cProfile            mistune             sqlite3             zlib
calendar            mmap                sqlparse            zmq
calltip             mmapfile            squeezer            zoneinfo
calltip_w           mmsystem            sre_compile         zoomheight
certifi             modulefinder        sre_constants       zzdummy
cffi                msilib              sre_parse           
cgi                 msvcrt              ssl                 
